### ISSUE TITLE
Dangling alt information on page break markers page

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/kb#114]
It seems that this information is there by mistake:
Definition
Alternative text is provided for visual content (e.g., via the [HTML] alt attribute).
Examples

This is found on:
https://kb.daisy.org/publishing/docs/metadata/schema.org/accessibilityFeature/pageBreakMarkers.html

**Comment by mattgarrish** [comment]
Thanks, yes, I likely used the alt text page as a template for splitting out all the values and forgot to update that definition. I'll get it fixed asap.
