### ISSUE TITLE
schema:accessibilityHazard are wrong

### ISSUE THREAD

**Issue by garconvacher** [daisy/kb#13]
Hi,

On the [Schema.org Accessibility Metadata](http://kb.daisy.org/publishing/docs/metadata/schema-org.html) page, I see:
```
  <meta property="schema:accessibilityHazard">noFlashing</meta>
  <meta property="schema:accessibilityHazard">noSound</meta>
  <meta property="schema:accessibilityHazard">noMotionSimulation</meta>
```
Correct values are noFlashingHazard, noSoundHazard and noMotionSimulationHazard
See: https://schema.org/accessibilityHazard

**Comment by mattgarrish** [comment]
Thanks, for the report. This has been fixed in https://github.com/daisy/kb/commit/830d3e8a971979eac943e76dd32a31c7694cccd5
