### ISSUE TITLE
missing Japanese pages

### ISSUE THREAD

**Issue by danielweck** [daisy/kb#134]
* http://kb.daisy.org/publishing/docs/html/links.html ==> `200`
* http://kb.daisy.org/publishing/ja/html/links.html ==> `404`

The main menu works: http://kb.daisy.org/publishing/ja/html/

...also `lang` http://kb.daisy.org/publishing/ja/html/lang.html

...also any page that's deeper that one-level: http://kb.daisy.org/publishing/docs/navigation/landmarks.html

**Comment by danielweck** [comment]
CC @mayuhamada

**Comment by danielweck** [comment]
LANG and LINKS now work (my original bug report above), but these pages are missing:

* http://kb.daisy.org/publishing/ja/script/
* http://kb.daisy.org/publishing/ja/text-to-speech/

**Comment by mattgarrish** [comment]
The site isn't fully translated, so closing this a non-issue at this time.
