### ISSUE TITLE
Japanese TOC becomes English

### ISSUE THREAD

**Issue by danielweck** [daisy/kb#141]
1) http://kb.daisy.org/publishing/ja/html/
2) Click on the "a" section (links) ==> http://kb.daisy.org/publishing/ja/html/links.html
3) Notice the "Categories" TOC on the right hand side, it is in English and it links to English pages.

+ @mayuhamada

**Comment by danielweck** [comment]
Same with the LANG page:
http://kb.daisy.org/publishing/ja/html/lang.html

**Comment by danielweck** [comment]
Also MAIN:
http://kb.daisy.org/publishing/ja/html/main.html

**Comment by danielweck** [comment]
Also META:
http://kb.daisy.org/publishing/ja/html/meta.html

**Comment by danielweck** [comment]
Also TITLE:
http://kb.daisy.org/publishing/ja/html/title.html

**Comment by danielweck** [comment]
Also SECTIONS:
http://kb.daisy.org/publishing/ja/html/sections.html

**Comment by danielweck** [comment]
Also SVG:
http://kb.daisy.org/publishing/ja/html/svg.html

**Comment by danielweck** [comment]
Also LISTS:
http://kb.daisy.org/publishing/ja/html/lists.html

**Comment by danielweck** [comment]
And MATHML:
http://kb.daisy.org/publishing/ja/html/mathml.html

**Comment by danielweck** [comment]
And OBJECT:
http://kb.daisy.org/publishing/ja/html/object.html

**Comment by danielweck** [comment]
Also QUOTES:
http://kb.daisy.org/publishing/ja/html/quotes.html

**Comment by danielweck** [comment]
And VIDEO:
http://kb.daisy.org/publishing/ja/html/video.html

**Comment by danielweck** [comment]
And MAPS:
http://kb.daisy.org/publishing/ja/html/maps.html

**Comment by danielweck** [comment]
I am sorry, there are too many to check ... could you please navigate each Japanese page link and note the broken ones :) Thank you

**Comment by mattgarrish** [comment]
This is a know issue we have with gitlocalize. It doesn't update the language of the html documents when translating. I fix all these manually after merging rather than check all the branches that come out of gitlocalize, but didn't have time yesterday. I'll have this updated before the end of weekend, so closing the issue.
