### ISSUE TITLE
recommended `accessibilityFeature` value is inconsistent with the authoritative W3C wiki

### ISSUE THREAD

**Issue by rdeltour** [daisy/kb#21]
`resizeText` is listed as a recommended `accessibilityFeature` value on the KB, but this value is not allowed by the authoritative list defined in the [W3C WebSchemas/Accessibility wiki page](https://www.w3.org/wiki/WebSchemas/Accessibility#Accessibility_terms_.28Version_2.0.29).

For this particular feature, the wiki recommends the value `displayTransformability` with the modifier `/font-size` (named after the CSS property).

Some other features recommended by the KB might be inconsistent too, I've not checked the full list.

**Comment by rdeltour** [comment]
> Some other features recommended by the KB might be inconsistent too, I've not checked the full list.

The following features are listed in the KB but not on the wiki:

- "enhancedAudio" (s/b "highContrastAudio"?)
- "highContrast" (s/b "highContrastDisplay")

**Comment by mattgarrish** [comment]
Ya, that's one seriously old version of the feature list (going back about six years now). I'll update when I have a minute.

**Comment by mattgarrish** [comment]
I've updated the feature and hazard lists to match the wiki in https://github.com/daisy/kb/commit/f35b174b9ced86e256fd7d2439f9a91037976be6
