### ISSUE TITLE
Alt tags in fixed layout EPUB images that go across the fold.

### ISSUE THREAD

**Issue by CircularKen** [daisy/kb#23]
Hi Daisy

Is there / what is the best practice for a significant image (so not a background) that crosses over the 'fold' in fixed layout EPUBs using synthetic spreads?

Assuming LTR reading I'm thinking we should we describe it once on the left page where the image appears first and then don't describe again on the right?

A danger in this approach would be viewing as single pages and landing the right hand page.

**Comment by mattgarrish** [comment]
If the images were in a single document, the normal practice would be to wrap them all in a figure tag and describe the first instance, leaving the others with empty alt tags and no description, so I'd say you have the right idea for FXL.

In the description on the first page, though, it would be useful to note that the image spans two pages. You could also (alternatively) incorporate the info into the alt text (e.g., the first image might have alt text like "xxx (page 1 of 2) and the second "xxx (page 2 of 2)". That might give a bit more of a clue if you land on the second page to go to the first to find the extended description.

You could indicate in the alt text for the second image to refer to the preceding page for the description, but it seems like it's going to be redundant information most of the time.

Any thoughts on this issue @GeorgeKerscher @avneeshsingh @clapierre ?

**Comment by clapierre** [comment]
I like where you are going with this Matt.  I think your suggestion of the figure tag should work if it encompasses both images so no matter the direction you go and if you reach image 1 first or image 2 first you should get that overarching figure description.  If that does not work then your idea of having 1of2 and 2of2 with a reference to the first image for a complete description is fine in my opinion.

**Comment by CircularKen** [comment]
The info from this recommendation is now in the KB here [https://paper.dropbox.com/doc/KB7-Fixed-Layouts-Multipage-Spreads--BJIdzwEpWJaFXidtjbo6qNAVAg-PwDYz1VPr26itMyINy3t9](url)
