### ISSUE TITLE
Typo: longDescription_s_

### ISSUE THREAD

**Issue by danielweck** [daisy/kb#24]
https://github.com/daisy/kb/blob/a91fe6a7d632940ff3b7811abf959a7e04b05109/publishing/docs/metadata/schema-org.html#L53

http://kb.daisy.org/publishing/docs/metadata/schema-org.html#ex

`<meta property="schema:accessibilityFeature">longDescriptions</meta>`

**Comment by mattgarrish** [comment]
Fixed in https://github.com/daisy/kb/commit/7b383edf64cc9d389e3ad744dbba1deba2c4d20e
