### ISSUE TITLE
accessibilityControl - fullAudioControl

### ISSUE THREAD

**Issue by danielweck** [daisy/kb#26]
http://kb.daisy.org/publishing/docs/metadata/schema-org.html#accessibilityControl

...shouldn't this be `fullVoiceControl` instead of `fullAudioControl`, as per:

https://www.w3.org/wiki/WebSchemas/Accessibility

?

**Comment by mattgarrish** [comment]
Thank, @danielweck. I thought I'd caught all the old values, but looks like the control values got missed. fullSwitchControl also wasn't in the list as it was added later.

This is fixed now in https://github.com/daisy/kb/commit/799da10bdbd82cdf149f80a6b54cb070abbb3766

(Now to figure out why I'm not getting alerts on this repository...)
