### ISSUE TITLE
Bug: incorrect "property" attribute for "link" element (should be "rel") in package OPF metadata

### ISSUE THREAD

**Issue by danielweck** [daisy/kb#28]
All the examples in:

http://kb.daisy.org/publishing/docs/metadata/evaluation.html#ex

Contrary to:

http://idpf.org/epub/301/spec/epub-publications.html#sec-link-elem

https://www.w3.org/publishing/epub3/epub-packages.html#sec-link-elem

http://idpf.org/epub/a11y/accessibility.html#sec-conf-reporting

**Comment by mattgarrish** [comment]
Thanks, fixed in https://github.com/daisy/kb/commit/2a37e0c057c28ce2e23857e969e524518777b445
