### ISSUE TITLE
Suggestion: Addition to EPUBCheck 'Alternatives' tools

### ISSUE THREAD

**Issue by MyDK** [daisy/kb#33]
The list of alternatives tools to EPUBCheck, on this page (scroll to the bottom):
http://kb.daisy.org/publishing/docs/epub/validation/epubcheck.html
does not contain the EPUBCheck plugin to Sigil (nor Calibre). 
- I wonder why? 

I suggest that the Sigil plugin is added to the Tool list either on KB. or on the GUI here.

Here is a link to the Sigil plugin on mobileread:
https://www.mobileread.com/forums/showthread.php?p=2950625#post2950625

**Comment by mattgarrish** [comment]
> The list of alternatives tools to EPUBCheck ... does not contain the EPUBCheck plugin to Sigil (nor Calibre). I wonder why?

It's not specifically a graphical interface for epubcheck, so I can see why it hasn't been listed on epubcheck's page. It may not have ever been submitted for inclusion.

I've added a third category for "integrated validation" for this and oxygen, which also isn't listed on that page: https://github.com/w3c/epubcheck/wiki/GUI

I've also added the IDPF validator, which was also missing. If you know of others you think should be listed, please open an issue in the epubcheck tracker.

Thanks!
