### ISSUE TITLE
Typo in Landmarks KB article

### ISSUE THREAD

**Issue by ThomasR128** [daisy/kb#36]
Line 2 of example 2 of the [Landmarks KB article](http://kb.daisy.org/publishing/docs/html/landmarks.html#ex-02) misses a "=". It should read `<h2 id="lo">Learning Objectives</h2>`

**Comment by mattgarrish** [comment]
Thanks, I've fixed this in https://github.com/daisy/kb/commit/86d4b0c7825a09853ede6aa70d00794ffb489c67
