### ISSUE TITLE
role="doc-cover"

### ISSUE THREAD

**Issue by RajeshVimal13** [daisy/kb#40]
The below recommended code is allowing JAWS to read the alt-text for the cover-images.

http://kb.daisy.org/publishing/docs/html/dpub-aria/doc-cover.html

ereader application: Vital source bookshelf

**Comment by mattgarrish** [comment]
Closing this issue as it's been open a long time and I'm not sure what's being reported here. If Jaws is working as expected, that's a great thing. If you meant it's not allowing access to the alt text, support is an open 
 issue per https://github.com/FreedomScientific/standards-support/issues/396
