### ISSUE TITLE
Possible typo in Footnote/Endnote KB article

### ISSUE THREAD

**Issue by ThomasR128** [daisy/kb#47]
[Example 1](http://kb.daisy.org/publishing/docs/html/notes.html#ex-01) says: `Use doc-endnote to group notes into lists.` Shouldn’t that read `Use doc-endnotes…`, since `doc-endnote` is deprecated?

Also, under [Note References](http://kb.daisy.org/publishing/docs/html/notes.html#note-refs), the backlink to Example 3 does not work – `#ex03` should probably be `#ex-03`.

Best regards,
Thomas

**Comment by mattgarrish** [comment]
Thanks for the report!

The issues are fixed in the latest commit.
