### ISSUE TITLE
Endnotes in WAI-ARIA Module 1.1 Draft

### ISSUE THREAD

**Issue by ThomasR128** [daisy/kb#48]
[Example 16](https://w3c.github.io/dpub-aria/#example-16) in the doc-endnotes section groups endnotes in a `<div role="list">` and wraps the individual endnotes in a `<div role="listitem">`. I understand this is meant for unnumbered notes, much like “blind” notes which, in an epub, of course could still have a backlink.

Since `<div>`s are not semantic elements: Wouldn’t it make more sense to group them with `<ul>` and `<li>` elements, similar to [Example 15](https://w3c.github.io/dpub-aria/#example-15)?

**Comment by mattgarrish** [comment]
The examples are intended to show both approaches: using the native semantic elements and not. But there's no difference between the two to an assistive technology, as the ARIA roles supplies the list and list item semantics that the div elements lack (i.e., the examples have same semantics in the accessibility tree).

If you can use `ul` and `ol` for lists, they're generally the better approach, but especially with EPUB, it's been a common problem that reading systems inconsistently apply list styling (e.g., hiding the automatically generated number or bullet doesn't work). We want people to still use the ARIA roles so the list semantics are available to AT users even if they style their notes without using lists.

**Comment by mattgarrish** [comment]
I'm a bit hesitant about writing the quirks of epub into the dpub-aria module. We were just discussing how we should make it clearer that the module is for any HTML content, so delving into reading system quirks sort of takes us in the opposite direction where people think the roles are not applicable to web-hosted publications.

It's definitely something we could document in the KB, though.

**Comment by ThomasR128** [comment]
Right, sounds more appropriate.
