### ISSUE TITLE
Documenting `a11y:certifiedBy` metadata property

### ISSUE THREAD

**Issue by jenstroeger** [daisy/kb#5]
The [accessibility checker `ace`](https://github.com/daisy/ace) checks for the existence of the `a11y:certifiedBy` metadata property, and refers to the [Accessibility Metadata page](http://kb.daisy.org/publishing/docs/metadata/schema-org.html). However, that page documents all _but_ that property.

Would be good if that missing information could be added.

**Comment by mattgarrish** [comment]
In the meantime, too, there is an explanation of this property (and the others we added) in the accessibility specification here: http://www.idpf.org/epub/a11y/#sec-conf-reporting

**Comment by jenstroeger** [comment]
@mattgarrish, thank you for the link. I’m now contemplating to use `ace` as the `certifiedBy` value because all of [Bookalope](https://bookalope.com.au/)’s generated books must pass through `ace`; it doesn’t seem like I’m able to specify more than one value though?

**Comment by mattgarrish** [comment]
If Ace is generating an error if you include the property more than once, please open an issue.

We didn't think it would be common to have multiple evaluators, but the property was intentionally left open to multiple declarations, as noted in the cardinality section in its definition: https://idpf.github.io/epub-vocabs/package/a11y/#sec-certifiedBy

**Comment by jenstroeger** [comment]
Using two `<meta property="a11y:certifiedBy">` worked.

However I noticed that [`epubcheck`](https://github.com/IDPF/epubcheck) gives me an error `Undeclared prefix: 'a11y'` (because I didn’t declare the `xmlns:a11y`... what’s its value?) and `ace` did not complain about the missing namespace. Not sure it matters but I guess it would be part of a consistency check… 🤔

**Comment by mattgarrish** [comment]
The a11y prefix is supposed to be "predefined", meaning you don't have to declare it, but it's always best to be explicit in the package file as whether it is accepted by epubcheck depends on what version is being used.

You need to use the prefix attribute for meta properties, like this:

<package … prefix="a11y: http://www.idpf.org/epub/vocab/package/a11y/#">

**Comment by mattgarrish** [comment]
Closing this issue as a page on the evaluation metadata has since been added: https://kb.daisy.org/publishing/docs/metadata/evaluation.html
