### ISSUE TITLE
HTML head meta charset UTF8 must be set before parsing, not after (otherwise Unicode characters are garbled)

### ISSUE THREAD

**Issue by danielweck** [daisy/kb#50]
Pre-parse (missing charset info):
https://github.com/daisy/kb/blob/436d88ddd8e161af797e9227259e79a802e91eed/publishing/docs/index.html#L1-L4

Post-parse (incorrect strategy):
https://github.com/daisy/kb/blob/436d88ddd8e161af797e9227259e79a802e91eed/js/init.js#L84-L88

To work around this bug in DAISY Ace App, we intercept the HTML and we inject the `<meta charset="utf-8">` markup on the "server side" when building the HTTP response, so that the "client side" browser engine (Chromium) parses the response body using the correct Unicode encoding.
See:
https://github.com/daisy/ace-gui/issues/153

**Comment by mattgarrish** [comment]
Thanks @danielweck. I didn't get a notice of this issue when it was opened, so only just spotted it now. The pages are meant to be stripped as bare as possible to make editing them easier, but if the missing charset is causing problems I'll add it back. Should have it done tomorrow.
