### ISSUE TITLE
Confusing table example

### ISSUE THREAD

**Issue by ThomasR128** [daisy/kb#51]
While I perfectly understand the practice described in [example 3](http://kb.daisy.org/publishing/docs/html/tables.html#ex-03) of the Tables KB article, I’m afraid I find the sample code rather confusing, code line 11 being identical to line 12, etc. 

Only after looking at the cited [source](https://archive.org/details/ost-business-tbq_reynolds_microeconomics_07/page/n277/mode/2up), it became clear to me that:

1. The second row in the KB example (code lines 10–16) is, in fact, the first data row of the original table – it looks more like a header row to me in the example,
2. The original table is awfully formatted and lacks a very necessary second header row, …
3. … which, in turn, would make it obvious that each year’s first column is a quintile value, and its second column is the cumulative value,
4. [Edward Tufte](https://www.edwardtufte.com/tufte/books_vdqi) would not approve 😉.

I would suggest to either add a ‘real’ second header row, or to choose a better example.

**Comment by ThomasR128** [comment]
Oh, the intent was perfectly clear to me. No need to hunt for another example, just add a second header row to the existing one, and call it a day. I’ll close the issue, and thanks for the great work on the KB – has helped me a lot. Looks like it’s mainly a one-man-show…

**Comment by mattgarrish** [comment]
> just add a second header row to the existing one, and call it a day

Unfortunately, it's cited from another source so I'm hesitant to tweak it. There's a better case for using the `headers` attribute in the explanation, but I'm sure I can make up another example.

I'll give the whole page a review while I'm at it. I see a copy/paste error in the second example that's incorrectly put 'scope="colgroup"` on the row spans. I also don't like how `headers` gets mentioned a lot when it should really be the last resort when the application isn't obvious or easily set using `scope`.

> Looks like it’s mainly a one-man-show…

Ha, I don't take all the credit. It's my job to keep things updated but I'm not alone in figuring out these practices. 😄
