### ISSUE TITLE
Minor typo in Line 8 of Example 1 on KB > HTML > Figures

### ISSUE THREAD

**Issue by brichwin** [daisy/kb#52]
In line 8 of Example 1 on the [KB > HTML > Figures page](http://kb.daisy.org/publishing/docs/html/figures.html) a closing quote for the class value appears to be missing.

Line 8 currently reads:
`<aside class="hidden id="img01-desc">`

With the addition of a double quote after the value hidden, It probably should read:
`<aside class="hidden" id="img01-desc">`

**Comment by mattgarrish** [comment]
Thanks, yes, definitely a typo! I'm on the road at the moment but will get this fixed as soon as I have a chance.
