### ISSUE TITLE
Broken links on the Metadata page

### ISSUE THREAD

**Issue by gautierchomel** [daisy/kb#56]
The [Metadata page](https://kb.daisy.org/publishing/docs/metadata/index.html) Schema.org section has all links broken. 

Example : https://kb.daisy.org/publishing/docs/metadata/accessibilityFeature.html leads to 404 error page.

**Comment by mattgarrish** [comment]
Yes, there was a problem with the topic sub-page not adding the schema.org directory to the hrefs (those pages are generated dynamically). It's fixed now, but you might need to do a hard refresh to get the new source.

Thanks for the report @gautierchomel!
