### ISSUE TITLE
dead link to dpub aria vocabulary at FAQ of ARIA role Attribute page

### ISSUE THREAD

**Issue by gautierchomel** [daisy/kb#58]
The first `dd` of http://kb.daisy.org/publishing/docs/html/roles.html#faq has a dead link (text extract: _If the [DPUB-ARIA vocabulary](http://kb.daisy.org/publishing/docs/html/dpub-aria.html) does not include a role..._

**Comment by mattgarrish** [comment]
Thanks for the report @gautierchomel! I've fixed this in https://github.com/daisy/kb/commit/8b73f3986bf955807f1d5a41935c4d2a81c1e1cf
