### ISSUE TITLE
Typo in closing tag

### ISSUE THREAD

**Issue by b-t-k** [daisy/kb#59]
http://kb.daisy.org/publishing/docs/html/bibliographies.html 
Example 1

```
<section role="doc-bibliography">
   <h1>Bibliography</h1>
   <dl>
     <dt>[pub-manfest]</dd>
     <dd></dd>
     …
   </dl>
</section>
```

Wrong closing tag for `<dt>[pub-manfest]</dd>`

**Comment by mattgarrish** [comment]
Thanks for the report! It's fixed in https://github.com/daisy/kb/commit/7191d1aee686eb58a7450b73dd94e07af2815db1
