### ISSUE TITLE
conformsTo contradiction between a11y 1.0 and 1.1 specs (IDPF WCAG URLs vs. strings)

### ISSUE THREAD

**Issue by danielweck** [daisy/kb#61]
http://kb.daisy.org/publishing/docs/metadata/evaluation.html
...links to undated specification:
https://www.w3.org/TR/epub-a11y/#sec-conf-reporting

**Comment by mattgarrish** [comment]
Thanks, @danielweck. I was waiting for the 1.1 specification to become a W3C Recommendation before updating the KB, but now that we've moved to a Proposed Recommendation it's probably safe to update the site.

**Comment by mattgarrish** [comment]
Closing as the site has been updated since 1.1 became a recommendation.
