### ISSUE TITLE
Images: Code sample of Example 5 — Hidden description

### ISSUE THREAD

**Issue by SarahMagdalena** [daisy/kb#9]
KB > HTML > Images

In the code sample **Example 5 — Hidden description**, the `<aside>`-element is not terminated by the matching end-tag `</aside>`.

**Comment by mattgarrish** [comment]
Thanks, yes, I'll try to get that fixed shortly.

**Comment by mattgarrish** [comment]
Fixed by https://github.com/daisy/kb/commit/39b9d39cd10640e4f012a720c03522d6254e2da2
